### ISSUE TITLE
outdated python3?

### ISSUE THREAD

**Issue by codedahmet** [Leeon123/TCP-UDP-Flood#3]
Traceback (most recent call last):
  File "/home/ahmet/Downloads/realtcp/flood.py", line 10, in <module>
    port = int(input(" Port:53"))
ValueError: invalid literal for int() with base 10: ''

help  and yes i renamed the folder to realtcp

**Comment by riccio8** [comment]
> Traceback (most recent call last): File "/home/ahmet/Downloads/realtcp/flood.py", line 10, in port = int(input(" Port:53")) ValueError: invalid literal for int() with base 10: ''
> 
> help and yes i renamed the folder to realtcp

Did u try to install  argparse? it could be an unresolved library
